import type { App, Component } from 'vue'

export { default as BaseAccordion } from './BaseAccordion.vue'
export { default as BaseAffix } from './BaseAffix.vue'
export { default as BaseAlert } from './BaseAlert.vue'
export { default as BaseAnchor } from './BaseAnchor.vue'
export { default as BaseAvatar } from './BaseAvatar.vue'
export { default as BaseAvatarGroup } from './BaseAvatarGroup.vue'
export { default as BaseBackTop } from './BaseBackTop.vue'
export { default as BaseBadge } from './BaseBadge.vue'
export { default as BaseBreadcrumb } from './BaseBreadcrumb.vue'
export { default as BaseBreadcrumbItem } from './BaseBreadcrumbItem.vue'
export { default as BaseButton } from './BaseButton.vue'
export { default as BaseButtonGroup } from './BaseButtonGroup.vue'
export { default as BaseCalendar } from './BaseCalendar.vue'
export { default as BaseCard } from './BaseCard.vue'
export { default as BaseCarousel } from './BaseCarousel.vue'
export { default as BaseCascader } from './BaseCascader.vue'
export { default as BaseCheckbox } from './BaseCheckbox.vue'
export { default as BaseCheckboxGroup } from './BaseCheckboxGroup.vue'
export { default as BaseCircleProgress } from './BaseCircleProgress.vue'
export { default as BaseCodeBlock } from './BaseCodeBlock.vue'
export { default as BaseColorPicker } from './BaseColorPicker.vue'
export { default as BaseCombobox } from './BaseCombobox.vue'
export { default as BaseCommandPalette } from './BaseCommandPalette.vue'
export { default as BaseCopyButton } from './BaseCopyButton.vue'
export { default as BaseCountdown } from './BaseCountdown.vue'
export { default as BaseDataTable } from './BaseDataTable.vue'
export { default as BaseDatePicker } from './BaseDatePicker.vue'
export { default as BaseDateRangePicker } from './BaseDateRangePicker.vue'
export { default as BaseDescriptions } from './BaseDescriptions.vue'
export { default as BaseDivider } from './BaseDivider.vue'
export { default as BaseDrawer } from './BaseDrawer.vue'
export { default as BaseDropdown } from './BaseDropdown.vue'
export { default as BaseEllipsis } from './BaseEllipsis.vue'
export { default as BaseEmptyState } from './BaseEmptyState.vue'
export { default as BaseFieldMessage } from './BaseFieldMessage.vue'
export { default as BaseFloatButton } from './BaseFloatButton.vue'
export { default as BaseForm } from './BaseForm.vue'
export { default as BaseFormItem } from './BaseFormItem.vue'
export { default as BaseGhostButton } from './BaseGhostButton.vue'
export { default as BaseHighlight } from './BaseHighlight.vue'
export { default as BaseImage } from './BaseImage.vue'
export { default as BaseInfiniteScroll } from './BaseInfiniteScroll.vue'
export { default as BaseInput } from './BaseInput.vue'
export { default as BaseKbd } from './BaseKbd.vue'
export { default as BaseLink } from './BaseLink.vue'
export { default as BaseListGroup } from './BaseListGroup.vue'
export { default as BaseListItem } from './BaseListItem.vue'
export { default as BaseLoading } from './BaseLoading.vue'
export { default as BaseLoadingBar } from './BaseLoadingBar.vue'
export { default as BaseLogo } from './BaseLogo.vue'
export { default as BaseMarquee } from './BaseMarquee.vue'
export { default as BaseMention } from './BaseMention.vue'
export { default as BaseMenu } from './BaseMenu.vue'
export { default as BaseModal } from './BaseModal.vue'
export { default as BaseNumberAnimation } from './BaseNumberAnimation.vue'
export { default as BaseNumberInput } from './BaseNumberInput.vue'
export { default as BasePagination } from './BasePagination.vue'
export { default as BasePanel } from './BasePanel.vue'
export { default as BasePanelTitle } from './BasePanelTitle.vue'
export { default as BasePinInput } from './BasePinInput.vue'
export { default as BasePopconfirm } from './BasePopconfirm.vue'
export { default as BasePopover } from './BasePopover.vue'
export { default as BaseProgress } from './BaseProgress.vue'
export { default as BaseRadio } from './BaseRadio.vue'
export { default as BaseRadioGroup } from './BaseRadioGroup.vue'
export { default as BaseRate } from './BaseRate.vue'
export { default as BaseResizablePanels } from './BaseResizablePanels.vue'
export { default as BaseResult } from './BaseResult.vue'
export { default as BaseRibbon } from './BaseRibbon.vue'
export { default as BaseScrollbar } from './BaseScrollbar.vue'
export { default as BaseSearchableSelect } from './BaseSearchableSelect.vue'
export { default as BaseSearchInput } from './BaseSearchInput.vue'
export { default as BaseSegmented } from './BaseSegmented.vue'
export { default as BaseSelect } from './BaseSelect.vue'
export { default as BaseSkeleton } from './BaseSkeleton.vue'
export { default as BaseSlider } from './BaseSlider.vue'
export { default as BaseSpin } from './BaseSpin.vue'
export { default as BaseStat } from './BaseStat.vue'
export { default as BaseStatusPill } from './BaseStatusPill.vue'
export { default as BaseStepper } from './BaseStepper.vue'
export { default as BaseSurface } from './BaseSurface.vue'
export { default as BaseSwitch } from './BaseSwitch.vue'
export { default as BaseTable } from './BaseTable.vue'
export { default as BaseTabs } from './BaseTabs.vue'
export { default as BaseTag } from './BaseTag.vue'
export { default as BaseTagsInput } from './BaseTagsInput.vue'
export { default as BaseTextarea } from './BaseTextarea.vue'
export { default as BaseTimeline } from './BaseTimeline.vue'
export { default as BaseTimePicker } from './BaseTimePicker.vue'
export { default as BaseToastContainer } from './BaseToastContainer.vue'
export { default as BaseToolbarButton } from './BaseToolbarButton.vue'
export { default as BaseTooltip } from './BaseTooltip.vue'
export { default as BaseTooltipProvider } from './BaseTooltipProvider.vue'
export { default as BaseTour } from './BaseTour.vue'
export { default as BaseTransfer } from './BaseTransfer.vue'
export { default as BaseTree } from './BaseTree.vue'
export { default as BaseTreeSelect } from './BaseTreeSelect.vue'
export { default as BaseUpload } from './BaseUpload.vue'
export { default as BaseVirtualList } from './BaseVirtualList.vue'
export { default as BaseWatermark } from './BaseWatermark.vue'
export { default as ImageModal } from './ImageModal.vue'
export {
  BASE_COMPONENT_API_DOCS,
  BASE_COMPONENT_COUNT,
  BASE_COMPONENT_GROUPS,
  BASE_COMPONENT_GROUP_SUMMARY,
} from './registry'

const componentModules = import.meta.glob<{ default: Component }>('./*.vue', { eager: true })

export const baseComponents = Object.fromEntries(
  Object.entries(componentModules).map(([path, module]) => {
    const name = path.split('/').pop()?.replace(/\.vue$/, '') || ''
    return [name, module.default]
  }),
)

export function install(app: App) {
  Object.entries(baseComponents).forEach(([name, component]) => {
    app.component(name, component)
  })
}

export default { install }
