export const BASE_COMPONENT_GROUPS = [
  {
    id: 'layout',
    label: '布局容器',
    components: [
      'BaseCard',
      'BaseDivider',
      'BasePanel',
      'BasePanelTitle',
      'BaseResizablePanels',
      'BaseSurface',
    ],
  },
  {
    id: 'form',
    label: '表单输入',
    components: [
      'BaseCheckbox',
      'BaseCombobox',
      'BaseDatePicker',
      'BaseFieldMessage',
      'BaseForm',
      'BaseFormItem',
      'BaseInput',
      'BaseNumberInput',
      'BaseRadio',
      'BaseRadioGroup',
      'BaseSearchableSelect',
      'BaseSearchInput',
      'BaseSelect',
      'BaseSlider',
      'BaseSwitch',
      'BaseTextarea',
      'BaseTimePicker',
      'BaseUpload',
    ],
  },
  {
    id: 'feedback',
    label: '反馈浮层',
    components: [
      'BaseAlert',
      'BaseCommandPalette',
      'BaseDrawer',
      'BaseLoading',
      'BaseModal',
      'BasePopconfirm',
      'BasePopover',
      'BaseProgress',
      'BaseSkeleton',
      'BaseToastContainer',
      'BaseTooltip',
      'BaseTooltipProvider',
    ],
  },
  {
    id: 'display',
    label: '数据展示',
    components: [
      'BaseAccordion',
      'BaseAvatar',
      'BaseBadge',
      'BaseCalendar',
      'BaseCodeBlock',
      'BaseDataTable',
      'BaseEmptyState',
      'BaseKbd',
      'BaseListGroup',
      'BaseListItem',
      'BaseLogo',
      'BaseStat',
      'BaseStatusPill',
      'BaseTable',
      'BaseTag',
      'BaseTree',
      'BaseVirtualList',
      'ImageModal',
    ],
  },
  {
    id: 'navigation',
    label: '导航操作',
    components: [
      'BaseBreadcrumb',
      'BaseBreadcrumbItem',
      'BaseButton',
      'BaseCopyButton',
      'BaseDropdown',
      'BaseGhostButton',
      'BaseMenu',
      'BasePagination',
      'BaseSegmented',
      'BaseStepper',
      'BaseTabs',
      'BaseToolbarButton',
    ],
  },
]

export const BASE_COMPONENT_API_DOCS = [
  { id: 1, component: 'BaseModal', props: 'open, title, icon, maxWidth, bodyClass', emits: 'close', slots: 'default, header, footer, icon' },
  { id: 2, component: 'BaseDrawer', props: 'open, title, placement, widthClass, closeOnBackdrop', emits: 'close', slots: 'default, footer' },
  { id: 3, component: 'BaseCommandPalette', props: 'open, items, placeholder', emits: 'update:open, select', slots: 'none' },
  { id: 4, component: 'BaseForm', props: 'disabled, loading, layout, gap', emits: 'submit', slots: 'default' },
  { id: 5, component: 'BaseInput', props: 'modelValue, label, type, error, inputClass', emits: 'update:modelValue', slots: 'append' },
  { id: 6, component: 'BaseTextarea', props: 'modelValue, label, maxlength, error, resize', emits: 'update:modelValue', slots: 'none' },
  { id: 7, component: 'BaseCheckbox', props: 'modelValue, value, label, indeterminate, error', emits: 'update:modelValue, change', slots: 'default' },
  { id: 8, component: 'BaseRadioGroup', props: 'modelValue, options, direction, error', emits: 'update:modelValue, change', slots: 'default' },
  { id: 9, component: 'BaseCombobox', props: 'modelValue, options, labelKey, valueKey, clearable', emits: 'update:modelValue, change', slots: 'none' },
  { id: 10, component: 'BaseDataTable', props: 'columns, rows, rowKey, pageSize, searchable', emits: 'row-click', slots: 'toolbar, cell-*' },
  { id: 11, component: 'BaseTable', props: 'columns, rows, rowKey, loading, compact', emits: 'sort, row-click', slots: 'cell-*' },
  { id: 12, component: 'BaseCalendar', props: 'modelValue, min, max', emits: 'update:modelValue, change', slots: 'none' },
  { id: 13, component: 'BaseTree', props: 'items, modelValue, defaultExpanded', emits: 'update:modelValue, select', slots: 'recursive item content' },
  { id: 14, component: 'BaseVirtualList', props: 'items, itemHeight, height, overscan', emits: 'none', slots: 'default' },
  { id: 15, component: 'BaseResizablePanels', props: 'modelValue, min, max', emits: 'update:modelValue, change', slots: 'left, right' },
  { id: 16, component: 'BasePopover', props: 'modelValue, placement, align, widthClass', emits: 'update:modelValue, open, close', slots: 'trigger, default' },
  { id: 17, component: 'BaseTooltipProvider', props: 'delay, offset, zIndex, disabled', emits: 'none', slots: 'default' },
  { id: 18, component: 'BaseButton', props: 'variant, size, to, href, type, disabled', emits: 'native click', slots: 'default' },
  { id: 19, component: 'BaseStepper', props: 'modelValue, steps, direction', emits: 'update:modelValue, change', slots: 'none' },
  { id: 20, component: 'BaseCodeBlock', props: 'code, language, title, copyable', emits: 'copy via BaseCopyButton', slots: 'none' },
]

export const BASE_COMPONENT_COUNT = BASE_COMPONENT_GROUPS.reduce(
  (total, group) => total + group.components.length,
  0,
)

export const BASE_COMPONENT_GROUP_SUMMARY = BASE_COMPONENT_GROUPS.map(group => ({
  id: group.id,
  label: group.label,
  count: group.components.length,
}))
